<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE tiles-definitions
    [
        <!ELEMENT component-definitions (definition+)>
        <!ELEMENT tiles-definitions (definition+)>
        <!ELEMENT definition (put*, putList*)>
        <!ATTLIST definition
            name CDATA #REQUIRED
            page CDATA #IMPLIED
            path CDATA #IMPLIED
            extends CDATA #IMPLIED
            role CDATA #IMPLIED
            template CDATA #IMPLIED
            controllerClass CDATA #IMPLIED
            controllerUrl CDATA #IMPLIED>
        <!ELEMENT put (#PCDATA)>
        <!ATTLIST put
            name CDATA #REQUIRED
            value CDATA #IMPLIED
            type (string | page | template | definition) #IMPLIED
            content CDATA #IMPLIED
            direct (true | false) #IMPLIED>
        <!ELEMENT putList ( (add* | item* | bean* | putList*)+) >
        <!ATTLIST putList
            name CDATA #REQUIRED>
        <!ELEMENT putListElements (add | item | bean)>
        <!ELEMENT add (#PCDATA)>
        <!ATTLIST add
            value CDATA #IMPLIED
            type (string | page | template | definition) #IMPLIED
            content CDATA #IMPLIED
            direct (true | false) #IMPLIED>
        <!ELEMENT bean (#PCDATA)>
        <!ATTLIST bean
            classtype CDATA #REQUIRED>
        <!ELEMENT item (#PCDATA)>
        <!ATTLIST item
            value CDATA #REQUIRED
            link CDATA #REQUIRED
            classtype CDATA #IMPLIED
            icon CDATA #IMPLIED
            tooltip CDATA #IMPLIED>
    ]>

<!-- Modificado por: Kerwin Arias (12/05/2012) -->

<tiles-definitions>

	<!-- =====================================================  -->
	<!-- Definiciones LAYOUT   									-->
	<!-- =====================================================  -->

	<!-- Layout que se muestra vacio -->
	<definition name="doc.cleanLayout" path="/componentes/marcos/cleanFrame.jsp">
		<put name="title" value="" />
		<put name="styleCss" value="/componentes/estilos/estilos.jsp" />
		<put name="jsCommons" value="/componentes/comunes/includeJsComunes.jsp" />
		<put name="body" value="" />
		<put name="messages" value="/componentes/mensajes/mensajes.jsp" />
		<put name="errorJsp" value="/componentes/error/errorJspNoFrame.jsp" />
		<put name="funcionesCierre" value="/componentes/comunes/funcionesCierre.jsp" />
	</definition>

	<!-- Layout por defecto de la aplicación -->
	<definition name="doc.loginLayout" path="/componentes/marcos/loginFrame.jsp">
		<put name="title" value="" />
		<put name="styleCss" value="/componentes/estilos/estilos.jsp" />
		<put name="jsCommons" value="/componentes/comunes/includeJsComunes.jsp" />
		<put name="messages" value="/componentes/mensajes/mensajes.jsp" />
		<put name="header" value="/componentes/encabezado/encabezado.jsp" />
		<put name="body" value="" />
		<put name="alertas" value="/componentes/alertas/alertas.jsp" />
		<put name="footer" value="/componentes/piePagina/piePagina.jsp" />
		<put name="barraProgreso" value="/componentes/barraProgreso/barraProgreso.jsp" />
		<put name="errorJsp" value="/componentes/error/errorJspNoFrame.jsp" />
		<put name="funcionesCierre" value="/componentes/comunes/funcionesCierre.jsp" />
	</definition>

	<!-- Layout por defecto de la aplicación -->
	<definition name="doc.defaultLayout" path="/componentes/marcos/defaultFrame.jsp">
		<put name="title" value="" />
		<put name="styleCss" value="/componentes/estilos/estilos.jsp" />
		<put name="jsCommons" value="/componentes/comunes/includeJsComunes.jsp" />
		<put name="messages" value="/componentes/mensajes/mensajes.jsp" />
		<put name="header" value="/componentes/encabezado/encabezado.jsp" />
		<put name="body" value="" />
		<put name="alertas" value="/componentes/alertas/alertas.jsp" />
		<put name="footer" value="/componentes/piePagina/piePagina.jsp" />
		<put name="barraProgreso" value="/componentes/barraProgreso/barraProgreso.jsp" />
		<put name="errorJsp" value="/componentes/error/errorJspNoFrame.jsp" />
		<put name="funcionesCierre" value="/componentes/comunes/funcionesCierre.jsp" />
	</definition>

	<!-- Layout principal de la aplicación -->
	<definition name="doc.mainLayout" path="/componentes/marcos/mainFrame.jsp">
   		<put name="title" value="" />
		<put name="styleCss" value="/componentes/estilos/estilos.jsp" />
		<put name="jsCommons" value="/componentes/comunes/includeJsComunes.jsp" />
		<put name="barraProgreso" value="/componentes/barraProgreso/barraProgreso.jsp" />
		<put name="messages" value="/componentes/mensajes/mensajes.jsp" />
		<put name="header" value="/componentes/encabezado/encabezado.jsp" />
		<put name="barraAplicacion" value="/componentes/barraAplicacion/barraAplicacion.jsp" />
		<put name="navigationBar" value="/componentes/barraNavegacion/barraNavegacion.jsp" />
		<put name="areaBar" value="/paginas/strategos/barraAreaStrategos.jsp" />
		<put name="body" value="" />
		<put name="alertas" value="/componentes/alertas/alertas.jsp" />
		<put name="footer" value="/componentes/piePagina/piePagina.jsp" />
		<put name="errorJsp" value="/componentes/error/errorJspNoFrame.jsp" />
		<put name="funcionesCierre" value="/componentes/comunes/funcionesCierre.jsp" />
	</definition>

	<!-- Layout para una ventana modal -->
	<definition name="doc.modalLayout" path="/componentes/marcos/modalFrame.jsp">
		<put name="title" value="" />
		<put name="styleCss" value="/componentes/estilos/estilos.jsp" />
		<put name="jsCommons" value="/componentes/comunes/includeJsComunes.jsp" />
		<put name="header" value="/componentes/encabezado/encabezado.jsp" />
		<put name="body" value="" />
		<put name="alertas" value="/componentes/alertas/alertas.jsp" />
		<put name="footer" value="/componentes/piePagina/piePagina.jsp" />
		<put name="messages" value="/componentes/mensajes/mensajes.jsp" />
		<put name="barraProgreso" value="/componentes/barraProgreso/barraProgreso.jsp" />
		<put name="errorJsp" value="/componentes/error/errorJspNoFrame.jsp" />
		<put name="funcionesCierre" value="/componentes/comunes/funcionesCierre.jsp" />
	</definition>

	<!-- Layout para una ventana modal Compatible con HTML5-->
	<definition name="doc.modalLayoutHTML5" path="/componentes/marcos/modalFrameHTML5.jsp">
		<put name="title" value="" />
		<put name="styleCss" value="/componentes/estilos/estilos.jsp" />
		<put name="jsCommons" value="/componentes/comunes/includeJsComunes.jsp" />
		<put name="header" value="/componentes/encabezado/encabezado.jsp" />
		<put name="body" value="" />
		<put name="alertas" value="/componentes/alertas/alertas.jsp" />
		<put name="footer" value="/componentes/piePagina/piePagina.jsp" />
		<put name="messages" value="/componentes/mensajes/mensajes.jsp" />
		<put name="barraProgreso" value="/componentes/barraProgreso/barraProgreso.jsp" />
		<put name="errorJsp" value="/componentes/error/errorJspNoFrame.jsp" />
		<put name="funcionesCierre" value="/componentes/comunes/funcionesCierre.jsp" />
	</definition>

	<!-- Layout para una ventana modal de error -->
	<definition name="doc.errorLayout" path="/componentes/marcos/modalFrame.jsp">
		<put name="title" value="" />
		<put name="styleCss" value="/componentes/estilos/estilos.jsp" />
		<put name="jsCommons" value="/componentes/comunes/includeJsComunes.jsp" />
		<put name="barraProgreso" value="/componentes/barraProgreso/barraProgreso.jsp" />
		<put name="messages" value="/componentes/mensajes/mensajes.jsp" />
		<put name="header" value="/componentes/encabezado/encabezado.jsp" />
		<put name="body" value="" />
		<put name="alertas" value="/componentes/alertas/alertas.jsp" />
		<put name="footer" value="/componentes/piePagina/piePagina.jsp" />
		<put name="errorJsp" value="" />
		<put name="funcionesCierre" value="/componentes/comunes/funcionesCierre.jsp" />
	</definition>

	<!-- Layout para una ventana de selector -->
	<definition name="doc.selectorLayout" path="/componentes/marcos/selectorFrame.jsp">
		<put name="title" value="" />
		<put name="styleCss" value="/componentes/estilos/estilos.jsp" />
		<put name="jsCommons" value="/componentes/comunes/includeJsComunes.jsp" />
		<put name="barraProgreso" value="/componentes/barraProgreso/barraProgreso.jsp" />
		<put name="messages" value="/componentes/mensajes/mensajes.jsp" />
		<put name="body" value="" />
		<put name="errorJsp" value="/componentes/error/errorJspNoFrame.jsp" />
		<put name="funcionesCierre" value="/componentes/comunes/funcionesCierre.jsp" />
	</definition>

	<!-- Layout para una ventana modal independiente -->
	<definition name="doc.modalWindowLayout" path="/componentes/marcos/modalWindowFrame.jsp">
		<put name="title" value="" />
		<put name="styleCss" value="/componentes/estilos/estilos.jsp" />
		<put name="jsCommons" value="/componentes/comunes/includeJsComunes.jsp" />
		<put name="barraProgreso" value="/componentes/barraProgreso/barraProgreso.jsp" />
		<put name="messages" value="/componentes/mensajes/mensajes.jsp" />
		<put name="body" value="" />
		<put name="errorJsp" value="/componentes/error/errorJspNoFrame.jsp" />
		<put name="funcionesCierre" value="/componentes/comunes/funcionesCierre.jsp" />
	</definition>

	<!-- Definiciones de Vistas o Páginas JSF -->
	<definition name=".defaultLayoutFaces" page="/pages/commons/inetrfaz/frames/defaultFrameFaces.faces">
		<put name="header" value="/pages/commons/header.jsp" />
		<put name="body" value="/pages/commons/blank.jsp" />
		<put name="messages" value="/pages/commons/messages.jsp" />
		<put name="barraProgreso" value="/pages/commons/barraProgreso.jsp" />
		<put name="jsCommons" value="/pages/commons/jsCommons.jsp" />
		<put name="footer" value="/pages/commons/footer.jsp" />
	</definition>

</tiles-definitions>
